# Generated by Django 5.1 on 2024-10-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbookhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
