# Generated by Django 5.1 on 2024-10-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbookhub', '0002_book_cover_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('published_date', models.IntegerField()),
                ('desciption', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
