# Generated by Django 5.1 on 2024-10-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbookhub', '0002_comment_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
