# Generated by Django 5.1 on 2024-10-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbookhub', '0003_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='desciption',
            new_name='description',
        ),
    ]
