# Generated by Django 5.1 on 2024-10-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbookhub', '0004_rename_desciption_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.CharField(max_length=10),
        ),
    ]
