# Generated by Django 5.1 on 2024-10-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbookhub', '0005_alter_books_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='authors',
        ),
    ]
